import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

/**
 * eslint-config-next 16 exports native flat-config arrays, so no FlatCompat shim
 * and no @eslint/eslintrc dependency are required.
 */

/**
 * `src/lib/env.core.ts` is the environment module without its `server-only` guard. That guard is
 * what makes a client component importing the environment a *build* error, so reaching past it
 * re-opens the hole it exists to close: a client component that imports the core builds cleanly
 * and ships a secret in prerendered HTML.
 *
 * Only `payload.config.ts` has a real reason to reach it - the `payload` CLI loads it through tsx,
 * outside Next, where `server-only` cannot resolve. Everything else imports `@/lib/env.server`.
 * See docs/ARCHITECTURE.md - D-14.
 */
const ENV_CORE_MESSAGE =
  'Import @/lib/env.server instead. env.core has no server-only guard, so importing it from a ' +
  'client component would build cleanly and leak secrets - see D-14.'

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      // Generated by `payload generate:types` / `payload generate:importmap`.
      // Committed, but never hand-edited and not ours to lint.
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      // Server/client boundary and correctness rules that the plan's Phase 2
      // edge-case list calls out explicitly.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/env.core', 'env.core', '**/env.core.js', '**/env.core.ts'],
              message: ENV_CORE_MESSAGE,
            },
          ],
        },
      ],

      // `no-restricted-imports` is blind to `import()`. Its rule implementation registers only
      // ImportDeclaration, ExportNamedDeclaration, ExportAllDeclaration and TSImportEqualsDeclaration
      // visitors - there is no ImportExpression among them - so the pattern above cannot see a
      // dynamic import at all.
      //
      // That is not academic. A client component doing `use(import('@/lib/env.core'))` passed
      // typecheck, lint AND build, and put the literal PAYLOAD_SECRET into the prerendered HTML of a
      // static route: the identical leak the static ban was added to close, reached by changing
      // `import x from` to `import(`. Found by the second Phase 4 audit; see notes §1.9.9.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportExpression > Literal[value=/(^|[\\\\/])env\\.core(\\.[jt]s)?$/]',
          message: ENV_CORE_MESSAGE,
        },
      ],
    },
  },
  {
    // The files that legitimately reach the unguarded core: `env.server.ts`, which is the guard and
    // re-exports it; the Payload config, which must stay resolvable under tsx; the instrumentation
    // hook, which runs before any React graph exists; and `scripts/`, added in Phase 6.
    //
    // `scripts/` qualifies for the same reason `payload.config.ts` does, and the reason is worth
    // stating because the exemption is security-relevant. The rule protects one thing: a *client
    // bundle* importing the environment and shipping a secret in prerendered HTML. A file under
    // `scripts/` cannot reach a client bundle — nothing in `src/` imports it, and it is run by the
    // Payload CLI through tsx, outside Next entirely. That is also why it cannot use the guarded
    // module: `env.server.ts` imports `server-only`, which throws under plain Node.
    //
    // The narrow risk this opens is a script importing something from `src/` that a route also
    // imports, dragging the core into a graph that is bundled. Nothing does, and the directory
    // boundary in plan §1.3 — `scripts/` is one-off local administration — is what keeps it that way.
    files: [
      'src/lib/env.server.ts',
      'src/payload.config.ts',
      'src/instrumentation.ts',
      'scripts/**/*.ts',
    ],
    rules: {
      'no-restricted-imports': 'off',
      'no-restricted-syntax': 'off',
    },
  },
  {
    // **Phase 30: two dependencies that must never be in the browser's first download again.**
    //
    // `env.public.ts` is reached by client components (MediaImage alone is rendered by four), so
    // anything it imports as a VALUE ships on every route. It imported Zod, and every storefront
    // route carried 65 KB gzip of it to re-check ten strings the server had already validated at
    // boot. The schema now lives in `env.schema.ts`; this file may take its TYPE and nothing else.
    //
    // `instrumentation-client.ts` and `global-error.tsx` are in every route's client graph by
    // construction. A static `@sentry/nextjs` import in either put ~58 KB gzip of SDK on every page
    // with no DSN configured. They load it with `import()` behind the build-time DSN check instead.
    //
    // `@typescript-eslint/no-restricted-imports` rather than the core rule, because it can allow
    // `import type` — which is erased and costs nothing — and because configuring the core rule here
    // would REPLACE the env.core ban above for these files rather than add to it.
    files: ['src/lib/env.public.ts', 'src/instrumentation-client.ts', 'src/app/global-error.tsx'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'zod',
              message:
                'Zod may not be imported here: this file is in every client bundle. Validate in env.schema.ts, which only env.core.ts imports.',
            },
            {
              name: '@sentry/nextjs',
              allowTypeImports: true,
              message:
                'Load the Sentry SDK with import() behind the NEXT_PUBLIC_SENTRY_DSN check. A static import ships it to every visitor, configured or not.',
            },
          ],
          patterns: [
            {
              group: ['**/env.schema', './env.schema'],
              allowTypeImports: true,
              message:
                'env.schema.ts imports Zod. Take the PublicEnv type with `import type`; never a value.',
            },
          ],
        },
      ],
    },
  },
]

export default config
