import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * **Phase 19 — the delivery record every transactional message gets.**
 *
 * Plan §2.2 lists *"email delivery event / idempotency record where needed"* among the required
 * conceptual entities, so this table is in the domain model rather than invented here.
 *
 * The line that matters is `CREATE UNIQUE INDEX "email_messages_dedupe_key_idx"`. §19.1c —
 * *"a webhook retry must not send two confirmation emails"* — is satisfied by that constraint and not
 * by any code: `send.ts` never asks whether a message was already sent, it claims the key by
 * inserting, and the violation **is** the answer. A read-then-write would have a window between the
 * read and the write, and two concurrent Stripe retries would both find nothing and both send. This
 * is the same mechanism `stripe-events.event_id` uses, chosen for the same reason.
 *
 * `data` is `jsonb` and nullable on purpose: a message carrying a single-use link stores nothing, so
 * a working password-reset token is never at rest in a table staff can read.
 *
 * Both relationships are `ON DELETE set null`, so deleting a customer or an order leaves the delivery
 * record standing. `to` and `subject` are the snapshot; the relationships are navigation.
 *
 * Generated by `payload migrate:create`, never hand-authored — `docs/DATABASE.md`. The only edit is
 * the parameter list, trimmed to what the body uses so the file passes `--max-warnings 0`.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_email_messages_kind" AS ENUM('contactConfirmation', 'orderConfirmation', 'orderDelivered', 'orderShipped', 'passwordReset', 'refund', 'verification', 'welcome');
  CREATE TYPE "public"."enum_email_messages_status" AS ENUM('failed', 'pending', 'sent', 'suppressed');
  CREATE TABLE "email_messages" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"dedupe_key" varchar NOT NULL,
  	"kind" "enum_email_messages_kind" NOT NULL,
  	"status" "enum_email_messages_status" DEFAULT 'pending' NOT NULL,
  	"to" varchar NOT NULL,
  	"subject" varchar NOT NULL,
  	"attempts" numeric DEFAULT 0 NOT NULL,
  	"last_attempt_at" timestamp(3) with time zone,
  	"sent_at" timestamp(3) with time zone,
  	"order_id" integer,
  	"customer_id" integer,
  	"provider_id" varchar,
  	"data" jsonb,
  	"error" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "email_messages_id" integer;
  ALTER TABLE "email_messages" ADD CONSTRAINT "email_messages_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "email_messages" ADD CONSTRAINT "email_messages_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "email_messages_dedupe_key_idx" ON "email_messages" USING btree ("dedupe_key");
  CREATE INDEX "email_messages_kind_idx" ON "email_messages" USING btree ("kind");
  CREATE INDEX "email_messages_status_idx" ON "email_messages" USING btree ("status");
  CREATE INDEX "email_messages_to_idx" ON "email_messages" USING btree ("to");
  CREATE INDEX "email_messages_order_idx" ON "email_messages" USING btree ("order_id");
  CREATE INDEX "email_messages_customer_idx" ON "email_messages" USING btree ("customer_id");
  CREATE INDEX "email_messages_provider_id_idx" ON "email_messages" USING btree ("provider_id");
  CREATE INDEX "email_messages_updated_at_idx" ON "email_messages" USING btree ("updated_at");
  CREATE INDEX "email_messages_created_at_idx" ON "email_messages" USING btree ("created_at");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_email_messages_fk" FOREIGN KEY ("email_messages_id") REFERENCES "public"."email_messages"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_email_messages_id_idx" ON "payload_locked_documents_rels" USING btree ("email_messages_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "email_messages" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "email_messages" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_email_messages_fk";
  
  DROP INDEX "payload_locked_documents_rels_email_messages_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "email_messages_id";
  DROP TYPE "public"."enum_email_messages_kind";
  DROP TYPE "public"."enum_email_messages_status";`)
}
