import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * **Phase 12 — one array table for the curated popular searches.**
 *
 * Decision D-38: plan §12.1c lists popular searches as a panel section and no document says where
 * they come from, so they are an editor-curated field on the `site-settings` global rather than a
 * read of Algolia analytics. The measured analytics corpus for this application has the empty string
 * as its top search by a factor of eighteen — every faceted /shop request sent an empty query — so a
 * list built from it would offer searches that lead to the no-results page.
 *
 * Generated by `pnpm migrate:create`, never hand-authored. The only edit is the parameter list,
 * trimmed to the `{ db }` this file actually uses, which is the convention every earlier migration
 * here follows and what keeps lint at --max-warnings 0.
 *
 * Longest generated identifier: `site_settings_search_popular_searches_parent_id_idx` at 51 bytes,
 * comfortably inside Postgres's 63-byte limit — the invariant `verify-home.ts` §M asserts globally.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "site_settings_search_popular_searches" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"term" varchar NOT NULL
  );
  
  ALTER TABLE "site_settings_search_popular_searches" ADD CONSTRAINT "site_settings_search_popular_searches_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "site_settings_search_popular_searches_order_idx" ON "site_settings_search_popular_searches" USING btree ("_order");
  CREATE INDEX "site_settings_search_popular_searches_parent_id_idx" ON "site_settings_search_popular_searches" USING btree ("_parent_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "site_settings_search_popular_searches" CASCADE;`)
}
