import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * **Phase 18 — what a refund records.**
 *
 * Plan §18.1b lists `PAID → REFUNDED` as an exceptional path and the schema had the *status* for it
 * since Phase 6. These two columns are the rest: a refund with no amount and no date is a word, and a
 * word cannot tell a partial refund from a full one. `refunded_minor` is the figure Stripe reports on
 * the `charge.refunded` event, in minor units like every other money column here.
 *
 * Both are nullable, because most orders are never refunded and `null` means *no refund* rather than
 * *nothing came back*. Both are written only from a signature-verified event, for the same reason
 * `paid_at` is: the money moved somewhere this application does not control, and the only trustworthy
 * account of it is the one that arrives signed.
 *
 * Nothing else in this phase touches the schema. The fulfilment machine, §18.1d's frozen snapshot
 * columns and the transition rules are all behaviour over columns that already existed — which is why
 * a phase this large adds two columns.
 *
 * Generated by `payload migrate:create`, never hand-authored — `docs/DATABASE.md`. The only edit is
 * the parameter list, trimmed to what the body uses so the file passes `--max-warnings 0`.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "orders" ADD COLUMN "refunded_at" timestamp(3) with time zone;
  ALTER TABLE "orders" ADD COLUMN "refunded_minor" numeric;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "orders" DROP COLUMN "refunded_at";
  ALTER TABLE "orders" DROP COLUMN "refunded_minor";`)
}
