import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * **Phase 17 — the Stripe webhook event record, and the order's link back to its bag.**
 *
 * Plan §17.1d requires a persisted event row whose **Stripe event id is unique**, and that uniqueness
 * is the point: it is the first of the phase's two idempotency barriers, and it works because it is a
 * database constraint rather than a check in a handler. Stripe retries an event until it is
 * acknowledged; a read-then-write guard has a window between the read and the write, and two
 * concurrent retries would both find nothing and both proceed. An insert that violates a unique index
 * has no window.
 *
 * `orders.cart_id` is §17.1a step 10's *"create or update pending order context"* — the key a second
 * checkout attempt uses to find the first attempt's order instead of creating another one. Nullable
 * and `ON DELETE SET NULL`, because an order is a snapshot and must survive the temporary row it came
 * from.
 *
 * Generated by `payload migrate:create`, never hand-authored — `docs/DATABASE.md`. The only edit is
 * the parameter list, trimmed to what the body uses so the file passes `--max-warnings 0`.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_stripe_events_status" AS ENUM('received', 'processed', 'ignored', 'failed');
  CREATE TABLE "stripe_events" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"event_id" varchar NOT NULL,
  	"type" varchar NOT NULL,
  	"received_at" timestamp(3) with time zone NOT NULL,
  	"status" "enum_stripe_events_status" DEFAULT 'received' NOT NULL,
  	"order_id" integer,
  	"error" varchar,
  	"attempts" numeric DEFAULT 1 NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "orders" ADD COLUMN "cart_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "stripe_events_id" integer;
  ALTER TABLE "stripe_events" ADD CONSTRAINT "stripe_events_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "stripe_events_event_id_idx" ON "stripe_events" USING btree ("event_id");
  CREATE INDEX "stripe_events_type_idx" ON "stripe_events" USING btree ("type");
  CREATE INDEX "stripe_events_status_idx" ON "stripe_events" USING btree ("status");
  CREATE INDEX "stripe_events_order_idx" ON "stripe_events" USING btree ("order_id");
  CREATE INDEX "stripe_events_updated_at_idx" ON "stripe_events" USING btree ("updated_at");
  CREATE INDEX "stripe_events_created_at_idx" ON "stripe_events" USING btree ("created_at");
  ALTER TABLE "orders" ADD CONSTRAINT "orders_cart_id_carts_id_fk" FOREIGN KEY ("cart_id") REFERENCES "public"."carts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_stripe_events_fk" FOREIGN KEY ("stripe_events_id") REFERENCES "public"."stripe_events"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "orders_cart_idx" ON "orders" USING btree ("cart_id");
  CREATE INDEX "payload_locked_documents_rels_stripe_events_id_idx" ON "payload_locked_documents_rels" USING btree ("stripe_events_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "stripe_events" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "stripe_events" CASCADE;
  ALTER TABLE "orders" DROP CONSTRAINT "orders_cart_id_carts_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_stripe_events_fk";
  
  DROP INDEX "orders_cart_idx";
  DROP INDEX "payload_locked_documents_rels_stripe_events_id_idx";
  ALTER TABLE "orders" DROP COLUMN "cart_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "stripe_events_id";
  DROP TYPE "public"."enum_stripe_events_status";`)
}
