import { toMinorAmount, toWholeCount } from '@/lib/money'

/**
 * **Plan §14's arithmetic, as pure functions.**
 *
 * *"All mutations must be server-authoritative."* (§14.1c) *"Do not trust totals generated by the
 * browser."* (§14.1d) Both sentences are about **where** the answer is computed, and this module is
 * the answer to a narrower question: where the answer is *decided*. Nothing here imports Next,
 * Payload or `server-only`, so `pnpm verify:cart` can walk every merge edge case §14.1b enumerates —
 * including the four that need two carts, a stock change and a deleted product in the same moment —
 * without a browser, a request or a database.
 *
 * The same split every phase since 9 has kept. `lib/cart/cart.ts` does the reads, the writes, the
 * cookie and the failure policy; it decides nothing.
 *
 * ---
 *
 * ### Quantities are clamped, never rejected
 *
 * A customer who asks for six of something with four in stock gets four and is told so. The
 * alternative — refusing the mutation — leaves them with the old quantity and an error, which is
 * worse in every way: they wanted more, more is not available, and the shop knows exactly how much
 * they can have. §14.1b's step 5 says the same thing about the merge (*"subject to stock/max
 * limits"*), and this module applies one rule to both paths so they cannot disagree.
 *
 * ### Two bounds, and they are different bounds
 *
 * `inventoryQuantity` is a fact about the warehouse. `maxQuantityPerLine` is merchandising policy
 * from `site-settings` — how many of one thing a shopper may buy at once — and `cart-items.quantity`
 * carries a hard schema cap of 99 on top of both. A clamp reports **which** bound bit, because "only
 * 4 left" and "10 per customer" are different sentences to read and the wrong one is misleading.
 */

/** The hard cap in `CartItems.ts`. A quantity above this cannot be stored, whatever policy says. */
export const QUANTITY_HARD_CAP = 99

/** One line, as the rules see it. Structural rather than a Payload type, so fixtures are cheap. */
export type CartLineInput = {
  productId: number
  quantity: number
  variantId: number
}

/** What the live catalogue says about a variant. `null` in a lookup means the row is gone. */
export type LineAvailability = {
  active: boolean
  inventoryQuantity: number
  /** `null` when the variant has no usable price, which makes it unbuyable. */
  priceMinor: null | number
  productPublished: boolean
}

export type ClampReason = 'policy' | 'soldOut' | 'stock' | null

export type ClampedQuantity = {
  /** Which bound bit, or `null` when the requested quantity was granted in full. */
  clampedBy: ClampReason
  quantity: number
}

/**
 * How many of this variant the customer may actually have.
 *
 * Zero is a real answer, and it means the line cannot exist — sold out, withdrawn, or unpriced. The
 * caller decides whether that is a removal or a refusal; this only decides the number.
 */
export function clampQuantity(
  requested: number,
  availability: LineAvailability | null,
  maxPerLine: number,
): ClampedQuantity {
  const policy = Math.max(1, Math.min(Math.floor(maxPerLine), QUANTITY_HARD_CAP))
  const wanted = toWholeCount(requested)

  if (
    !availability ||
    !availability.active ||
    !availability.productPublished ||
    availability.priceMinor === null
  ) {
    return { clampedBy: 'soldOut', quantity: 0 }
  }

  const stock = toWholeCount(availability.inventoryQuantity)

  if (stock === 0) {
    return { clampedBy: 'soldOut', quantity: 0 }
  }

  if (wanted > stock && stock <= policy) {
    return { clampedBy: 'stock', quantity: stock }
  }

  if (wanted > policy) {
    return { clampedBy: 'policy', quantity: Math.min(policy, stock) }
  }

  return { clampedBy: null, quantity: wanted }
}

/* -------------------------------------------------------------------------------------------------
 * Merge — plan §14.1b
 * ---------------------------------------------------------------------------------------------- */

export type MergedLine = CartLineInput & {
  /** True when this variant was in both bags and the quantities were summed. */
  combined: boolean
}

export type MergeAdjustment = {
  /** Why the line is not what the customer asked for. */
  reason: Exclude<ClampReason, null>
  requested: number
  resolved: number
  variantId: number
}

export type MergeResult = {
  /** Lines that could not survive the merge at all. */
  dropped: MergeAdjustment[]
  lines: MergedLine[]
  /** Lines that survived at a smaller quantity than the sum. */
  reduced: MergeAdjustment[]
}

/**
 * **Plan §14.1b, all seven steps.**
 *
 * > 1. Load guest cart. 2. Load customer cart. 3. Merge line items by variant. 4. Revalidate
 * > availability and quantity. 5. Resolve duplicate items by summing quantities subject to stock/max
 * > limits. 6. Remove invalid products. 7. Preserve the correct resulting cart.
 *
 * Steps 1 and 2 are reads and belong to the caller. Everything from 3 is here.
 *
 * ### Why the customer's own lines lead
 *
 * The output order is the customer's bag first, then whatever the guest session added. It is a small
 * thing and it is the difference between signing in and finding your bag with new things in it, and
 * signing in and finding a stranger's ordering of your own bag. Within each group the input order is
 * preserved, so the result is a function of its inputs and nothing else — which is what lets the
 * harness assert it.
 *
 * ### Summing, then clamping, in that order
 *
 * Two of three in one bag and three of three in the other is a request for five, and five is what
 * gets checked against stock — not two checks that each pass. §14.1b's *"quantity exceeds stock
 * after merge"* edge case exists precisely because the sum can fail where the parts did not, and a
 * merge that clamped each side first would silently produce a bag holding more than the warehouse
 * has.
 *
 * A line whose variant is gone, withdrawn or sold out is **dropped**, not zeroed — §14.1b step 6,
 * and the two remaining edge cases (*"one variant becomes unavailable during merge"*, *"product
 * deleted while guest was browsing"*) are the same code path. Both are reported, because a bag that
 * quietly loses a line is a bag the customer will not trust.
 */
export function mergeCartLines(
  customer: CartLineInput[],
  guest: CartLineInput[],
  availability: Map<number, LineAvailability | null>,
  maxPerLine: number,
): MergeResult {
  /**
   * **`inBoth` rather than a count of occurrences — Phase 27's first sweep.**
   *
   * This was `sources += 1` over the concatenated `[...customer, ...guest]`, so a variant appearing
   * **twice inside one bag** came back `combined: true`. That contradicts the field's own
   * documentation — *"true when this variant was in both bags"* — and it is not a hypothetical: a
   * bag holds one row per variant by design, but nothing in this pure function enforces that, and
   * the caller passes rows read from the database.
   *
   * Which bag a line came from is the fact being recorded, so that is what is tracked.
   */
  const wanted = new Map<
    number,
    { fromCustomer: boolean; fromGuest: boolean; line: CartLineInput }
  >()

  for (const [source, lines] of [
    ['customer', customer],
    ['guest', guest],
  ] as const) {
    for (const line of lines) {
      const existing = wanted.get(line.variantId)

      if (existing) {
        existing.line = { ...existing.line, quantity: existing.line.quantity + line.quantity }
        existing.fromCustomer ||= source === 'customer'
        existing.fromGuest ||= source === 'guest'
      } else {
        wanted.set(line.variantId, {
          fromCustomer: source === 'customer',
          fromGuest: source === 'guest',
          line: { ...line },
        })
      }
    }
  }

  const dropped: MergeAdjustment[] = []
  const lines: MergedLine[] = []
  const reduced: MergeAdjustment[] = []

  for (const [variantId, { fromCustomer, fromGuest, line }] of wanted) {
    const clamped = clampQuantity(line.quantity, availability.get(variantId) ?? null, maxPerLine)

    if (clamped.quantity <= 0) {
      /**
       * **`soldOut` only when it is — Phase 27's first sweep.**
       *
       * The fallback was `clamped.clampedBy ?? 'soldOut'`, and `clampQuantity` returns
       * `{ clampedBy: null, quantity: 0 }` for a request of **zero** against a variant with plenty
       * of stock. A merge carrying a zero-quantity row therefore told the customer their garment
       * had sold out when it had not — a false statement about inventory, produced by a default.
       *
       * There is no `ClampReason` for "you asked for none", and inventing one would widen a union
       * three other call sites switch on. `stock` is wrong for the same reason `soldOut` is. So the
       * row is simply **not reported**: nothing was dropped, because nothing was asked for.
       */
      if (clamped.clampedBy === null) {
        continue
      }

      dropped.push({
        reason: clamped.clampedBy,
        requested: line.quantity,
        resolved: 0,
        variantId,
      })

      continue
    }

    if (clamped.quantity < line.quantity) {
      reduced.push({
        reason: clamped.clampedBy ?? 'stock',
        requested: line.quantity,
        resolved: clamped.quantity,
        variantId,
      })
    }

    lines.push({ ...line, combined: fromCustomer && fromGuest, quantity: clamped.quantity })
  }

  return { dropped, lines, reduced }
}

/* -------------------------------------------------------------------------------------------------
 * Totals — plan §14.1d
 * ---------------------------------------------------------------------------------------------- */

export type PricedLine = {
  quantity: number
  unitPriceMinor: number
}

/**
 * **What a bag costs, and what is not yet knowable.**
 *
 * §14.1d asks for subtotal, discount, shipping estimate, tax estimate *"where appropriate"*, and
 * total. Exactly one of those five can be computed truthfully in this phase.
 *
 * `null` is therefore load-bearing and is **not** the same as `0`. A discount of zero says *no
 * discount applies*; a discount of `null` says *this phase does not know, and the surface must not
 * imply that it does*. Promotions are **Phase 15**, shipping rates and tax are **Phase 16**, and
 * writing a confident `£0.00` beside either would be plan §0.1.17's fake UI expressed as a number —
 * the most persuasive kind, because a customer has no way to tell a computed zero from a placeholder.
 *
 * `isFinal` is what the UI reads to decide between *"Total"* and *"Subtotal — shipping and tax
 * calculated at checkout"*. It is false while anything is `null`. Phase 15 filled `discount` and
 * Phase 16 filled `shipping`; `tax` is still `null` on every bag, because tax is a function of a
 * destination and the address form belongs to checkout. No component changed for either of those to
 * start rendering, which was the property this shape was built for.
 */
export type CartTotals = {
  /** Phase 15. `null` until promotions can be validated. */
  discountMinor: null | number
  /** True only when every component is known. */
  isFinal: boolean
  itemCount: number
  /** Phase 16. */
  shippingMinor: null | number
  subtotalMinor: number
  /** Phase 16. */
  taxMinor: null | number
  /** The sum of what is known. Equal to the subtotal while the rest is `null`. */
  totalMinor: number
}

export function cartTotals(
  lines: PricedLine[],
  /**
   * The discount Phase 15's engine computed for this bag, or `null` when no code is applied.
   *
   * `null` and `0` are still different: `null` means *no promotion*, and the row is not drawn; `0`
   * means a promotion is applied and currently takes nothing off, which the customer needs to see
   * because it is surprising. Phase 16 fills `shipping` and `tax` the same way.
   */
  discount: null | number = null,
  /**
   * The shipping amount Phase 16's provider quoted, or `null` when none has been quoted.
   *
   * A *quote* is enough to fill this: the static provider prices from the cart rather than from the
   * destination, so a bag with no address still has an honest number. What it does not have is
   * confirmed **eligibility**, which is why the bag labels it an estimate.
   */
  shipping: null | number = null,
  /**
   * The tax amount, or `null` when it is not known — which is every bag today, because tax is a
   * function of a destination and no surface collects one before checkout.
   *
   * `null` and `0` are different claims: `0` says no tax is owed, and a checkout acting on a `0` that
   * really meant *unknown* would undercharge every order in a taxable jurisdiction.
   */
  tax: null | number = null,
): CartTotals {
  let subtotalMinor = 0
  let itemCount = 0

  for (const line of lines) {
    const quantity = toWholeCount(line.quantity)

    /*
     * **An unpriced line is counted but not charged for, and Phase 27's sweep left that alone.**
     *
     * A `unitPriceMinor` of null, NaN or infinity becomes `0` here, so its units reach `itemCount`
     * while contributing nothing to the subtotal — a bag that reports three items and charges for
     * two. Phase 27's unit tests flagged it as a null-means-unknown collapse, and the case for
     * changing it is real.
     *
     * It was not changed, for two reasons. `lib/cart/cart.ts` filters on
     * `unitPriceMinor !== null && maxQuantity > 0` **before** calling this, so no unpriced line
     * reaches it on any live path — the shape is defensive only. And the existing behaviour is a
     * written decision rather than an oversight: §14.1e wants an unavailable line **visible**, and a
     * count that silently dropped it would hide the discrepancy the bag is trying to show. Making
     * an unreachable path disagree with a documented decision is not a fix.
     */
    subtotalMinor += toMinorAmount(line.unitPriceMinor) * quantity
    itemCount += quantity
  }

  /*
   * `discountMinor` is Phase 15's, and arrives as an argument. Shipping and tax are Phase 16's and
   * are still `null` — typed rather than inferred, because `const x = null` narrows to the literal
   * `null`, which would make the `!== null` below a comparison TypeScript can prove and whoever
   * tidied the warning would delete `isFinal` with it.
   */
  const discountMinor: null | number =
    discount === null ? null : Math.min(toMinorAmount(discount), subtotalMinor)
  const shippingMinor: null | number = shipping === null ? null : toMinorAmount(shipping)
  const taxMinor: null | number = tax === null ? null : toMinorAmount(tax)

  return {
    discountMinor,
    /*
     * **Two questions were conflated here, and the harness found it.**
     *
     * `null` was doing two jobs: *do not draw this row* and *this component is unknown*. For shipping
     * and tax they are the same thing. For a **discount** they are not — a bag with no code applied
     * has `discountMinor: null` and a perfectly knowable total, because no discount contributes
     * nothing. Requiring it made `isFinal` unreachable for every bag without a code, which is most
     * of them.
     *
     * So `isFinal` asks only about the components that can be *unknown*: a discount that is absent is
     * known to be zero.
     */
    isFinal: shippingMinor !== null && taxMinor !== null,
    itemCount,
    shippingMinor,
    subtotalMinor,
    taxMinor,
    totalMinor:
      Math.max(0, subtotalMinor - (discountMinor ?? 0)) + (shippingMinor ?? 0) + (taxMinor ?? 0),
  }
}

/* -------------------------------------------------------------------------------------------------
 * Shipping progress — plan §14.1e
 * ---------------------------------------------------------------------------------------------- */

export type ShippingProgress = {
  /** `0`–`1`, for a progress indicator. `1` once the threshold is met. */
  fraction: number
  qualified: boolean
  remainingMinor: number
}

/**
 * How far the bag is from free delivery.
 *
 * `freeShippingThresholdMinor` is an editor's number in `site-settings`, and its own description
 * points here. A threshold of zero means everything ships free, which is a configuration a shop may
 * genuinely choose — so it qualifies rather than dividing by zero.
 *
 * This is the **only** part of §14.1d's shipping estimate this phase can compute, and it is
 * computable because it is a comparison against the subtotal rather than a rate for a destination.
 * The rate is Phase 16.
 */
export function shippingProgress(
  subtotalMinor: number,
  thresholdMinor: null | number,
): null | ShippingProgress {
  if (thresholdMinor === null || !Number.isFinite(thresholdMinor) || thresholdMinor < 0) {
    return null
  }

  const subtotal = toMinorAmount(subtotalMinor)
  const threshold = Math.floor(thresholdMinor)

  if (threshold === 0) {
    return { fraction: 1, qualified: true, remainingMinor: 0 }
  }

  return {
    fraction: Math.min(1, subtotal / threshold),
    qualified: subtotal >= threshold,
    remainingMinor: Math.max(0, threshold - subtotal),
  }
}

/* -------------------------------------------------------------------------------------------------
 * Copy
 * ---------------------------------------------------------------------------------------------- */

/**
 * Every sentence the bag can say, in one place.
 *
 * The same reason `SEARCH_COPY` exists: a message written at its call site is a message that drifts
 * from the message three files away that means the same thing, and a harness can assert a constant
 * but not a template literal buried in JSX.
 */
export const CART_COPY = {
  empty: 'Your bag is empty.',
  emptyDetail: 'Nothing has been added yet.',
  /** §14.1e's *"cart request fails"*. */
  failed: 'We could not load your bag just now. Refresh the page to try again.',
  /** §14.1e's *"product becomes unavailable"* — the line is still shown, and cannot be bought. */
  lineUnavailable: 'No longer available',
  mutationFailed: 'That did not save. Your bag has been reloaded — please try again.',
  /** Shown once, above the lines, after a merge or a revalidation changed something. */
  revalidated: 'Your bag was updated to match what is in stock.',
  soldOut: 'Sold out',
} as const

/** The sentence for a clamp, or `null` when the customer got what they asked for. */
export function clampNotice(clamped: ClampedQuantity): null | string {
  switch (clamped.clampedBy) {
    case 'policy':
      return `You can add up to ${clamped.quantity} of this per order.`
    case 'soldOut':
      return 'That size is sold out.'
    case 'stock':
      return clamped.quantity === 1
        ? 'Only one left, so we added one.'
        : `Only ${clamped.quantity} left, so that is what we added.`
    default:
      return null
  }
}
